### ISSUE TITLE
Syntax Highlighting error

### ISSUE THREAD

**Issue by lethargilistic** [gi0baro/weppy-website#1]
Heya, minor thing. In the docs page for [dal/operations](http://weppy.org/docs/1.0/dal/operations), the "String and text operators" section has some strange syntax highlighting. It seems like the % symbol is triggering a switch to red from green. This is probably upstream of you, and is the concern of whoever wrote the highlighting system you're using, but I figured you'd be more capable of looking into it, if you care.

**Comment by gi0baro** [comment]
@lethargilistic thank you for pointing this out. Probably deactivating the auto-detection in HighlightJS and manually set the language in the code blocks should work. I will post an update on this soon.

**Comment by gi0baro** [comment]
@lethargilistic I've switched the docs linter to pygments. Should work better now.
